var feeds = [
    'NOS Nieuws Algemeen,https://feeds.nos.nl/nosnieuwsalgemeen',
    'NOS Nieuws Binnenland,https://feeds.nos.nl/nosnieuwsbinnenland',
    'NOS Nieuws Buitenland,https://feeds.nos.nl/nosnieuwsbuitenland',
    'NOS Nieuws Politiek,https://feeds.nos.nl/nosnieuwspolitiek',
    'NOS Nieuws Economie,https://feeds.nos.nl/nosnieuwseconomie',
    'NOS Nieuws Opmerkelijk,https://feeds.nos.nl/nosnieuwsopmerkelijk',
    'NOS Nieuws Koningshuis,https://feeds.nos.nl/nosnieuwskoningshuis',
    'NOS Nieuws Cultuur en media,https://feeds.nos.nl/nosnieuwscultuurenmedia',
    'NOS Nieuws Tech,https://feeds.nos.nl/nosnieuwstech',
    'NOS Sport Algemeen,https://feeds.nos.nl/nossportalgemeen',
    'NOS Sport Voetbal,https://feeds.nos.nl/nosvoetbal',
    'NOS Sport Wielrennen,https://feeds.nos.nl/nossportwielrennen',
    'NOS Sport Schaatsen,https://feeds.nos.nl/nossportschaatsen',
    'NOS Sport Tennis,https://feeds.nos.nl/nossporttennis',
    'NOS Sport Formule 1,https://feeds.nos.nl/nossportformule1',
    'Nieuwsuur,https://feeds.nos.nl/nieuwsuuralgemeen',
    'NOS op 3,https://feeds.nos.nl/nosop3',
    'NOS Jeugdjournaal,https://feeds.nos.nl/jeugdjournaal',
    'NOS Nieuws Video,https://feeds.nos.nl/nosnieuwsvideo',
    'NOS Sport Schaatsen Video,https://feeds.nos.nl/nossportschaatsenvideo',
    'NOS Sport Wielrennen Video,https://feeds.nos.nl/nossportwielrennenvideo',
    'NOS Sport Voetbal Video,https://feeds.nos.nl/nossportvoetbalvideo',
    'NOS Sport Tennis Video,https://feeds.nos.nl/nossporttennisvideo',
    'NOS Sport Formule 1 Video,https://feeds.nos.nl/nossportformule1video',
];
